apiVersion: v1
kind: Service
metadata:
  name: avisvc-lb
  namespace: planespotter
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    name: eighty
  selector:
    app: avi-server
